project:
  type: website

website:
  title: "Zhou Bolin's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zhoubolin0404
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

